# Generated by Django 2.2.6 on 2020-01-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва правіла')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Тэкст')),
            ],
            options={
                'verbose_name': 'Правіла',
                'verbose_name_plural': 'Правілы',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Заданне', 'verbose_name_plural': 'Заданні'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Адказ'),
        ),
        migrations.AddField(
            model_name='task',
            name='question',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тэкст заданія'),
        ),
        migrations.CreateModel(
            name='ExplanationOfTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=250, null=True, verbose_name='Агульнае заданне')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.Regulation')),
            ],
            options={
                'verbose_name': 'Заданне да практыкавання',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='explanation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='trainer.ExplanationOfTask'),
            preserve_default=False,
        ),
    ]
