# Generated by Django 2.2.6 on 2020-01-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20200116_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationoftask',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Агульнае заданне'),
            preserve_default=False,
        ),
    ]
