# Generated by Django 2.2.6 on 2020-01-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20200116_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explanationoftask',
            options={'verbose_name': 'Заданне для практыкавання'},
        ),
    ]
