# Generated by Django 2.2.6 on 2020-01-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20200116_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.CharField(blank=True, max_length=150, verbose_name='Тэкст заданія'),
        ),
    ]
