# Generated by Django 2.2.6 on 2020-01-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20200116_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationoftask',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.Regulation', verbose_name='Правіла'),
        ),
        migrations.AlterField(
            model_name='task',
            name='explanation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.ExplanationOfTask', verbose_name='Агульнае заданне'),
        ),
    ]
