# Generated by Django 2.2.6 on 2020-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20200117_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Адказ'),
        ),
    ]
