# Generated by Django 2.2.6 on 2020-04-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_auto_20200419_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.TextField(blank=True, verbose_name='Тэкст заданія'),
        ),
    ]
