# Generated by Django 2.2.6 on 2020-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Вопыт карыстальніка'),
        ),
    ]
