# Generated by Django 2.2.6 on 2020-04-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200416_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', height_field='height_field', null=True, upload_to='profile_pics', width_field='width_field'),
        ),
    ]
